### ISSUE TITLE
Навести порядок в способах хранения структуры модели

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/raox#29]
Структура модели хранится сейчас с частичным дублированием в трех местах:

- в базе данных в формате `JSON`: [link](https://github.com/bogachev-pa/rdo-xtext/blob/dev/ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/Database.java#L141)
- в симуляторе как объект класса `ModelStructureCache`: [link](https://github.com/bogachev-pa/rdo-xtext/blob/dev/ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/Simulator.java#L56) - изначально класс был создан для более быстрого доступа к структуре модели из трассировщика.
- небольшие части так же дублируются в индексах базы данных: [link](https://github.com/bogachev-pa/rdo-xtext/blob/dev/ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/CollectedDataNode.java#L144)

Необходимо навести здесь порядок и хранить всю структуру в одном месте или, как минимум, четко разделить, на каком этапе используются обращения к структуре в формате `JSON`, а на каком к кэшированной структуре.

Начало обсуждения тут:
https://github.com/k-alexandrovsky/rdo-xtext/pull/37#discussion_r31376247

Связана с:
- [ ] [Продумать предоставление данных ModelStructureCache для ui](https://github.com/aurusov/rdo-xtext/issues/62)

**Comment by aurusov** [comment]
Для себя. Обсуждение началось с более простого - переименования локальных переменных.

**Comment by bogachev-pa** [comment]
Сделано в ветке с `xbase`.
