### ISSUE TITLE
Использовать сторонние библиотеки как jar вместо копипасты исходного кода

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/raox#35]
@aurusov
@k-alexandrovsky

Сторонние библиотеки, например, математические либы, которые требуются рантайму, в данный момент добавлены в либу рдо в виде исходного кода. Требует использовать для этих целей джарники.

**Comment by bogachev-pa** [comment]
Почему закрыто? Задача не решена.

**Comment by aurusov** [comment]
Перепутал с thirdparty

**Comment by bogachev-pa** [comment]
Решено в ветке `feature/xbase`. Т.к. таска в моем форке, и это моя основная ветка, то сразу закрываю.
