### ISSUE TITLE
Legacy-Tracer

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/raox#6]
Связана с:
- [x] k-alexandrovsky/rdo-xtext#20

@aurusov
@k-alexandrovsky

Необходимо уметь выводить трассировку в формате, эквивалентном формату старого РДО.

Тут есть три опции:
1. `LegacyTracer` - отдельный модуль. Работает непосредственно с базой данный и её байтбуфером и не зависит от трассировщика.
[+] Неважно, в каком формате будет сохранять строки основной трассировщик (модульность - наше всё)
[+] По сути, он практически написан, за небольшими исключениями это текущий основной трассировщик.
[-] Предположительно будет копипаста и, наверняка, немало.
2. `LegacyTracer` - отдельный модуль. Работает со строковым выводом трассировщика.
[+] Если изменения не будут колоссальными, то модуль будет небольшим и достаточно простым.
[-] Модуль зависит от основного трассировщика и его придется менять, если изменится вывод последнего.
[-] В какой-то момент изменения в трассировке могут оказаться такими, что нам будет недостаточно `JSON`-структуры модель для конвертации. Тогда нам придется обращаться к байт-буферу и это полное фиаско.
3. `LegacyTracer` - это особенный режим работы основного трассировщика.
[+] Вероятно, добавит меньше всего кода.
[+] Практически не будет копипасты.
[-] Код трассировщика будет замусорен легаси-кодом. 

Я лично за первый вариант. С копипастой еще можно будет как-то бороться (например, забирать у основного трассировщика кэшированные данные о модели и helper-методы, область видимости которых можно сделать package), а вот минусы двух других подходов, по-моему, перевешивают их плюсы.

**Comment by bogachev-pa** [comment]
Сделал для легаси-трассировщика вывод вещественных чисел в формате, соответсвующем формату `RAO-studio` (https://github.com/bogachev-pa/rdo-xtext/commit/e9ecadf560cc1a3b8e1b2ce016415ca4a8e2ad55), в связи с чем возник вопрос, а какой формат мы хотим в новом РДО?

В старом было так:
Выводится 6 значащих цифр числа, пока это возможно (т.е. пока не достигли миллиона, например `54.5567`, `6789.62`, `556894`), потом выводится 6 значащих цифр в научной нотации (например, `5.05505e+06).
Конвертировать в такой вывод оказалась несколько страшной и корявой, потому что встроенных методов, позволяющих так выводить, я не нашел. В итоге пришлось писать то, что видите в коде коммита.

Если в новом хотим такой же формат, то надо будет померить, не проседает ли производительность на этих всех форматированиях и, если да, что-то придумывать.

**Comment by aurusov** [comment]
В старом используется фортам Borland Pascal. Держаться за него не надо. У нас нет никаких причин модифицировать стандартный Java-формат. Так что для легаси надо сделать, а для нового ничего делать не надо.

Что-то еще осталось по этой таске ?

**Comment by bogachev-pa** [comment]
>Что-то еще осталось по этой таске ?

Да, у меня начинает незначительно отличаться вывод для моделей со случайными распределениями, и я еще не проверял основательно поиск по графу и деревообработку. На днях сделаю это и выложу сюда результаты.

**Comment by bogachev-pa** [comment]
Поправил вывод для результата поиска на графе. Теперь для поиска осталось вроде всего одно несовпадение по формату:
В старом РДО не выводятся значения ресурсов при инициализации, если мы проводим поиск по графу, т.е. в старом:
```
ES 0 1
ES 0 3
```
а в новом:
```
ES 0 1
RK 0 1 1 1 2
RK 0 1 2 2 3
RK 0 1 3 3 6
RK 0 1 4 4 4
RK 0 1 5 5 5
RK 0 2 6 1
ES 0 3
```
Я не очень понимаю, как это реализовано в старом РДО (т.е. как он понимает до начала прогона, ждет его обычная модель или поиск по графу), и я не очень понимаю, как это можно отличить в новом, чтобы эти записи убрать.

Помимо этого, вопросы только с самому поиску по графу, у меня процесс поиска отличается для старого и нового РДО, хотя результаты и одинаковые.

**Comment by aurusov** [comment]
>В старом РДО не выводятся значения ресурсов при инициализации, если мы проводим поиск по графу

Выглядит как ошибка в старом РДО. Посмотришь ?

**Comment by aurusov** [comment]
>Помимо этого, вопросы только с самому поиску по графу, у меня процесс поиска отличается для старого и нового РДО, хотя результаты и одинаковые

Тут сложнее. Это может быть логической ошибкой в одной из реализаций. Если их проанализировать и доказать, что это не так (оба решения правильные), то возможно два варианта:
- свести один к другому (после самого сложного этапа - анализа - это будет несложно imho)
- во время сравнения с помощью регулярок выкидывать тело трассировки, сравнивать только результат - не полное, но приемлемое решение для многих кейсов. Очень плохое в случает отсутствия решения.

**Comment by bogachev-pa** [comment]
>Выглядит как ошибка в старом РДО. Посмотришь ?

В общем, всё нормально, это я напутал. Думал, что `trace_all` в `Decision_point` должен автоматически включить трассировку ресурсов, но он это делает только на время процесса поиска по графу. Если вручную проставить везде `Фишка1.trace();`, то здесь все одинаково.

>Тут сложнее. Это может быть логической ошибкой в одной из реализаций. 

@k-alexandrovsky 
Скорее всего, ошибка в новом РДО, и, судя по всему, она при обработке уже встречавшихся вершин. Потому что по трассировке видно, что там, где должен был быть `STD`, мы имеем `STN`. В итоге некоторые вершины добавляются в граф дважды. Подробнее может, наверное, пояснить @kstrizhov.

**Comment by bogachev-pa** [comment]
@k-alexandrovsky
В общем, мы сейчас с Кириллом повникали в процесс поиска по графу, и нашли несколько косяков.
1. Совпадающие вершины, которые оказались хуже, уже имеющихся (`WORSE`), не сериализуются вообще. `break add_child` [здесь](https://github.com/k-alexandrovsky/rdo-xtext/blob/generator/ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/DecisionPointSearch.java#L271) приводит к тому, что мы не попадаем в строку с серализацией [здесь](https://github.com/k-alexandrovsky/rdo-xtext/blob/generator/ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/DecisionPointSearch.java#L300).
2. Зачем производится поиск для смены родителя также и для списка `closed`?
В алгоритме на вики (http://en.wikipedia.org/wiki/A*_search_algorithm#Pseudocode), в случае нахождения вершины в `closed`, мы выходим из цикла сразу и даже не пытаемся сменить родителя. В твоем алгоритме, мы проводим для них такие же операции, как для списка `opened` (см. [здесь](https://github.com/k-alexandrovsky/rdo-xtext/blob/generator/ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/DecisionPointSearch.java#L274)).
3. Еще вопрос. В чем отличие величин `nodes total` и `nodes added`? Почему-то они всегда отличаются для нового РДО, даже когда совпадают для старого.

**Comment by aurusov** [comment]
<b>2</b>. Да, тоже обратил на это внимание на лекциях недавно. Надо в белой книжке Люгера посмотреть. Походу это избыточная операция в РДО.

>Edit: что-то я совсем запутался, смены родителя, что в твоем алгоритме, что в алгоритме с вики нет вообще, только замена текущей вершины на лучшую.

Вообще-то да. Надо не только заменить вершину, но и обновить стоимость ```g``` всех её потомков.

**Comment by k-alexandrovsky** [comment]
Так, стоп. Если в closed мы ничего не меняем (что автоматически означает, что `g` как минимум не уменьшается в процессе поиска, т.е. стоимость применения правил может быть только положительной), то нам не надо обновлять стоимость потомков, потому что у вершин в списке open потомков нет.
  
**Вики:**
>**Remark:** the above pseudocode assumes that the heuristic function is *monotonic* (or *consistent*, see below), which is a frequent case in many practical problems, such as the Shortest Distance Path in road networks. However, if the assumption is not true, nodes in the **closed** set may be rediscovered and their cost improved. In other words, the closed set can be omitted (yielding a tree search algorithm) if a solution is guaranteed to exist, or if the algorithm is adapted so that new nodes are added to the open set only if they have a lower f value than at any previous iteration.
  
А если мы все же честно копаемся в closed (в РДО можно указать отрицательную стоимость, в новом у точно), то при "замене" вершины на самом деле происходит удаление старой из графа вообще (сейчас так), а новая попадает в список open, без потомков, они будут созданы после, обновлять снова ничего не надо.
  
С другой стороны, можно действительно вместо добавления свеженькой вершины подменять потомка у уже существующей, а потом рекурсивно бежать по детям и обновлять им стоимость. Это дает выигрыш в производительности, равный времени проверки активностей. Тогда надо только применять активности и обновлять стоимости у всей ветки. Это быстрее, и мне это нравится, алгоритм я перепишу.

**Comment by k-alexandrovsky** [comment]
@bogachev-pa 
**3**. Имеется в виду
```
SE<признак>
    <модельное_время>
    <время_счета>
    <объем_памяти_для_поиска>
    <значение_стоимости_решения>
    <количество_раскрытых_вершин>
    <количество_вершин_в_графе> <===============|  это
    <количество_включавшихся_в_граф_вершин> <===| и это?
    <количество_порожденных_вершин>
```
 Тут я вообще не понимаю, как они могут различаться, потому что это
```java
	.putInt(nodesOpen.size() + nodesClosed.size())
	.putInt(totalAdded)
```
Надо сидеть и отлаживаться, похоже что. Зато я знаю, почему у нас разные графы. Я сначала порождаю детей, а проверяю terminate, когда достаю вершину из списка open, а надо при порождении детей проверять terminate, мало ли, сколько там их порождается, может десять тысяч, а мы могли уже найти одного нужного.

**Comment by aurusov** [comment]
>Я сначала порождаю детей, а проверяю terminate, когда достаю вершину из списка open, а надо при порождении детей проверять terminate, мало ли, сколько там их порождается, может десять тысяч, а мы могли уже найти одного нужного.

Лучше всегда вытаскивать из open, потому что на последнем шаге может оказаться два ребёнка-решения. И у второго стоимость g может оказаться меньше (кто сказал, что она всегда == 1).

**Comment by k-alexandrovsky** [comment]
Хм, тогда я не понимаю, почему отличается вывод. Надо поковыряться.
@aurusov 
По поводу проверки closed я правильно понял? Может нам сделать какой нибудь флаг, разрешающий/запрещающий отрицательные стоимости. Или анализировать список, только если стоимость применения на текущем шаге оказалась меньше нуля. А при положительной стоимости забивать на closed. Или тут какие то подводные камни, которых я не вижу?

**Comment by aurusov** [comment]
>анализировать список, только если стоимость применения на текущем шаге оказалась меньше нуля

Недостаточно imho. В общем случае надо думать о монотонности. Мне кажется, что достаточно всегда проверять closed и не переживать из-за этого. Остальное назвать преждевременной оптимизацией. Если возникнет потребность, то добавим параметр.

PS: Посмотрел у Люгера - надо проверять и в списке closed. Так что на вики алгоритм надо читать с учетом замечания. Что выглядит как ошибка блин - ты первый, кто его прочитал ил моих знакомых :)

**Comment by kstrizhov** [comment]
По ходу нашел еще один косяк. Количество открытых вершин есть количество вершин, для которых мы породили потомков. Если я ничего не путаю, то в собираемой статистике у нас всегда на 1 вершину больше, чем есть на самом деле.

![2015-01-21 14-03-19 _ _2](https://cloud.githubusercontent.com/assets/9355661/5835301/0e6e182a-a178-11e4-84dd-d864fffe1195.png)
![2015-01-21 14-14-55 _](https://cloud.githubusercontent.com/assets/9355661/5835304/1288c086-a178-11e4-8f04-dd7f5b9b4788.png)

**Comment by aurusov** [comment]
Всё хорошо, но не сходится трассировка
* DPT Search
* любые генераторы псевдослучайных чисел

**Comment by bogachev-pa** [comment]
@aurusov,

Нужно ли мне все еще продолжать поддержку легаси трассировщика после перехода на `xbase`?

**Comment by aurusov** [comment]
Это нужно для тестов, которых у нас нет. Пока нет тестов, можно не замаричиваться. Но в любой момент задача может появиться, тогда хотелось бы добавить без рефакторинга.

**Comment by bogachev-pa** [comment]
Окей. Просто на случай, если бы мы вдруг отказались от концепции принятия старого рдо за эталон.

**Comment by bogachev-pa** [comment]
Продолжение тут: https://github.com/aurusov/raox/issues/356
